### PR TITLE
Front-end update

### PR DESCRIPTION
**Pull request by jackhkmatthews**
Hey Rassibassi,

We've got to a V1 of the updated front-end https://doyoutrackid.com

- from vanilla React to NextJS
- from s3 to Vercel hosting (deployed on commit to jackhkmatthews/doyoutrackid:main)
- from bulma CSS to custom SCSS and designs

Let me know what you think 👍

### CODE REVIEW

**Comment by Rassibassi** [comment]
amazing job :) with domain and everything! If Im ever in the UK again, Ill get you a pint :)

**Comment by jackhkmatthews** [comment]
Ha, glad you like it! And thanks for creating this, has been a lot of fun to work on what you already had in place.

Yeah for sure, that would be great 👍 

Me and Erin (the designer) are planning to 'release' it on Monday. Basically, just post on insta and spam the chat a little during the show. Fingers crossed we all get a shout out 🤞

**Comment by Rassibassi** [comment]
ups, I already linked it on the old page. Ill remove that link

**Comment by Rassibassi** [comment]
Oh and you put some details into the env variable file which you might want to remove :/

**Comment by Rassibassi** [comment]
would it be possible for you add the confetti as in here: https://github.com/Rassibassi/doyoutrackid/tree/confetti
on the 13th of January ;), such that it happens automatically every year

**Comment by Rassibassi** [comment]
hej! great job, it was well received today I think. I kept an eye on the chat.

A little update, I am in the Copenhagen timezone, so the 11:11 feature triggered cph time, rather than UK time :(

would it be possible to make the site trigger the 11:11 feature at UK time, no matter what time zone you are in?

:)

**Comment by jackhkmatthews** [comment]
> Oh and you put some details into the env variable file which you might want to remove :/

Oops, which one's should be removed? I thought I only left public safe values in there?

**Comment by Rassibassi** [comment]
here, your email is in there, if you don't mind

https://github.com/Rassibassi/doyoutrackid/blob/main/frontend/.env.development

**Comment by jackhkmatthews** [comment]
> would it be possible for you add the confetti as in here: https://github.com/Rassibassi/doyoutrackid/tree/confetti on the 13th of January ;), such that it happens automatically every year

Ah that's a great idea! 

For frontend updates how about we open PR's against my forked repo, merge into master, deploy, and then merge back into this repo.

If that sounds good could you open a confetti PR on the forked repo?

**Comment by jackhkmatthews** [comment]
> hej! great job, it was well received today I think. I kept an eye on the chat.
> 
> A little update, I am in the Copenhagen timezone, so the 11:11 feature triggered cph time, rather than UK time :(
> 
> would it be possible to make the site trigger the 11:11 feature at UK time, no matter what time zone you are in?
> 
> :)

Ah good spot! Yes I'll add that to my to-do list and update

**Comment by Rassibassi** [comment]
> > would it be possible for you add the confetti as in here: https://github.com/Rassibassi/doyoutrackid/tree/confetti on the 13th of January ;), such that it happens automatically every year
> 
> Ah that's a great idea!
> 
> For frontend updates how about we open PR's against my forked repo, merge into master, deploy, and then merge back into this repo.
> 
> If that sounds good could you open a confetti PR on the forked repo?

That'll work, but I'm affraid I do not speak any typescript :( so I cannot work on the frontend without investing some time learning ts. I can try though, we do have a whole year for the feature though

**Comment by jackhkmatthews** [comment]
No worries! I can use your branch and create my own commit 👍

**Pull request merged**
